version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "35432:5432"
  app:
    restart: on-failure
    build: .
    environment:
      - host=lallah.db.elephantsql.com
      - user=isrhdnag
      - pass=hEIxLnFR2us893BgnC8T7y3hpUTTlh57
      - schema=isrhdnag
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
